"""
05_infer_time_to_onset.py
Inference for TFT (time_to_onset) with PyTorch>=2.6 safe-load fix.

Key fix:
- load_from_checkpoint(..., weights_only=False)
"""

from pathlib import Path
import pandas as pd

from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import GroupNormalizer


def main():
    # ✅ use your actual best checkpoint path
    ckpt_path = Path(r"outputs/checkpoints/tft_time_to_onset-epoch=25-val_loss=0.2669.ckpt")
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")

    data_path = Path("data/processed/chloride_labeled.parquet")
    df = pd.read_parquet(data_path)

    # Only series with observed onset (time_to_onset is not NaN)
    df = df[df["time_to_onset"].notna()].copy()

    max_encoder_length = 52
    max_prediction_length = 13

    training_cutoff = df["time_idx"].max() - max_prediction_length

    dataset = TimeSeriesDataSet(
        df[df.time_idx <= training_cutoff],
        time_idx="time_idx",
        target="time_to_onset",
        group_ids=["series_id"],
        max_encoder_length=max_encoder_length,
        max_prediction_length=max_prediction_length,
        time_varying_known_reals=["time_idx", "t_year"],
        time_varying_unknown_reals=["chloride_rebar", "time_to_onset"],
        static_reals=["Cs", "cover_m", "D28", "m_aging", "C_th"],
        target_normalizer=GroupNormalizer(groups=["series_id"]),
        add_relative_time_idx=True,
        add_target_scales=True,
        add_encoder_length=True,
    )

    dl = dataset.to_dataloader(train=False, batch_size=64, num_workers=0)

    # ✅ PyTorch 2.6+ safe-load fix:
    # checkpoint is generated by you, so it is trusted → allow full load
    model = TemporalFusionTransformer.load_from_checkpoint(str(ckpt_path), weights_only=False)

    # Get predictions for the next horizon for each sample
    # preds shape: [n_samples, prediction_length]
    preds = model.predict(dl).cpu().numpy()

    out_dir = Path("outputs/predictions")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Save raw predictions (for later alignment/metrics)
    out_path = out_dir / "time_to_onset_preds_raw.npy"
    import numpy as np
    np.save(out_path, preds)

    print("✅ Loaded checkpoint:", ckpt_path)
    print("✅ Saved raw predictions:", out_path)
    print("preds shape =", preds.shape)


if __name__ == "__main__":
    main()
